# Site settings
title: Votainteligente 2016
email: info@ciudadanointeligente.org
description: SE AVECINA UNA NUEVA ELECCIÃ“N MUNICIPAL.
baseurl: "https://ciudadanointeligente.github.io/comingsoon" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: ciudadanoi

# Build settings
markdown: kramdown
